--MIG_TAKE_OVER_D_COMMITMENT
--10,624


WITH CTE AS(
SELECT DISTINCT  RTRIM(LTRIM(OVER_D.K_KEY)) K_KEY, CASE WHEN OVER_D.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
OVER_D.AMOUNT, CASE WHEN CONVERT(VARCHAR(MAX),DISCAP2.DSAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP2.DSMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP2.DSDVCP)),2) < 20210621 THEN 1 ELSE CASE WHEN (DISCAP2.DSSALD-DISCAP2.DSMATA ) = 0 THEN 1 ELSE (DISCAP2.DSSALD-DISCAP2.DSMATA ) END END AMOUNT_AUDITORIA
FROM MIG_TAKE_OVER_D_COMMITMENT OVER_D
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) = RTRIM(LTRIM(CREDIT.CANUCR)) 
LEFT JOIN (SELECT  * FROM CADISCAP) DISCAP2
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) = RTRIM(LTRIM(DISCAP2.CANUCR))
AND OVER_D.AMOUNT = CASE WHEN CONVERT(VARCHAR(MAX),DISCAP2.DSAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP2.DSMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP2.DSDVCP)),2) < 20210621 THEN 1 ELSE CASE WHEN (DISCAP2.DSSALD-DISCAP2.DSMATA ) = 0 THEN 1 ELSE (DISCAP2.DSSALD-DISCAP2.DSMATA ) END END

)

--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE  K_KEY <> K_KEY_AUDITORIA


--SELECT AMOUNT,AMOUNT_AUDITORIA FROM CTE
--WHERE  AMOUNT <> AMOUNT_AUDITORIA



--SELECT MATURITY_DATE,MATURITY_DATE_AUDITORIA FROM CTE
--WHERE  MATURITY_DATE <> MATURITY_DATE_AUDITORIA


