-- MIG_CAPTURE_BAL_D_MAINTENANCE
--21,248

WITH CTE AS(
--10,624
SELECT 
K_KEY,
K_KEY_AUDITORIA,
CASE WHEN NEW_BAL_AMT = 0 THEN NULL ELSE NEW_BAL_AMT END AS NEW_BAL_AMT,
NEW_BAL_AMT_AUDITORIA
FROM(
SELECT DISTINCT MAIN.K_KEY, CASE WHEN MAIN.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
	MAIN.NEW_BAL_AMT,  (CASE
    WHEN abs((CAST(DISCAP2.dssald AS NUMERIC(13,2)) - CAST(DISCAP2.dsmata AS NUMERIC(13,2)))) = 0 THEN 1
    ELSE abs((CAST(DISCAP2.dssald AS NUMERIC(13,2)) - CAST(DISCAP2.dsmata AS NUMERIC(13,2))))
  END * -1) NEW_BAL_AMT_AUDITORIA
FROM MIG_CAPTURE_BAL_D_MAINTENANCE MAIN
LEFT JOIN CACREDIT CREDIT
ON  RTRIM(LTRIM(RIGHT(MAIN.K_KEY,7))) = RTRIM(LTRIM(CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,dssald,dsmata FROM CADISCAP) DISCAP2
ON RTRIM(LTRIM(RIGHT(MAIN.K_KEY,7))) =  RTRIM(LTRIM(DISCAP2.CANUCR))
AND 	MAIN.NEW_BAL_AMT =  (CASE
    WHEN abs((CAST(DISCAP2.dssald AS NUMERIC(13,2)) - CAST(DISCAP2.dsmata AS NUMERIC(13,2)))) = 0 THEN 1
    ELSE abs((CAST(DISCAP2.dssald AS NUMERIC(13,2)) - CAST(DISCAP2.dsmata AS NUMERIC(13,2))))
  END * -1) 
WHERE MAIN.ADJUST_PROP =  'ACCOUNT'  
AND MAIN.ADJ_BAL_TYPE = 'CURACCOUNT'
UNION ALL
--10,624
SELECT DISTINCT MAIN.K_KEY, CASE WHEN MAIN.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
MAIN.NEW_BAL_AMT, (CAST(ROUND(dsinpr,2,1) AS DECIMAL(18,2))) * -1  NEW_BAL_AMT_AUDITORIA
FROM MIG_CAPTURE_BAL_D_MAINTENANCE MAIN
LEFT JOIN CACREDIT CREDIT
ON  RTRIM(LTRIM(RIGHT(MAIN.K_KEY,7))) = RTRIM(LTRIM(CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,dsinpr FROM CADISCAP) DISCAP2
ON RTRIM(LTRIM(RIGHT(MAIN.K_KEY,7))) =  RTRIM(LTRIM(DISCAP2.CANUCR))
AND MAIN.NEW_BAL_AMT = (CAST(ROUND(dsinpr,2,1) AS DECIMAL(18,2))) * -1  
WHERE MAIN.ADJUST_PROP =  'PRINCIPALINT'  
AND MAIN.ADJ_BAL_TYPE = 'ACCPRINCIPALINT'
)X
)

----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY , K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY <> K_KEY_AUDITORIA


----NEW_BAL_AMT VS NEW_BAL_AMT_AUDITORIA
--SELECT K_KEY,NEW_BAL_AMT , NEW_BAL_AMT_AUDITORIA FROM CTE
--WHERE NEW_BAL_AMT <> NEW_BAL_AMT_AUDITORIA