--MIG_TAKE_OVER_D_XTIDOM
--10,624


--WITH CTE AS(
SELECT RTRIM(LTRIM(OVER_D.K_KEY))K_KEY,  CASE WHEN OVER_D.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
OVER_D.STATUS_TIDOM, CASE   
    WHEN CREDIT.CAORFF < 900    
        THEN 1 
    WHEN CREDIT.CAORFF >= 900   
        THEN 3 
    ELSE 
        0 
END 
    AS STATUS_TIDOM_AUDITORIA
FROM MIG_TAKE_OVER_D_XTIDOM OVER_D
LEFT JOIN CACREDIT CREDIT 
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) =  RTRIM(LTRIM(CREDIT.CANUCR))
--)

--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY<>K_KEY_AUDITORIA


SELECT STATUS_TIDOM,STATUS_TIDOM_AUDITORIA FROM CTE
WHERE STATUS_TIDOM<>STATUS_TIDOM_AUDITORIA
