--MIG_TAKE_OVER_D_ACCOUNT
--10,636

WITH CTE AS(
SELECT RTRIM(LTRIM(OVER_D.ALT_ID)) ALT_ID, CASE WHEN OVER_D.ALT_ID = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END ALT_ID_AUDITORIA
FROM MIG_TAKE_OVER_D_ACCOUNT OVER_D
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(RIGHT(OVER_D.ALT_ID,7))) = RTRIM(LTRIM(CREDIT.CANUCR)) 
)

SELECT ALT_ID,ALT_ID_AUDITORIA FROM CTE
WHERE  ALT_ID <> ALT_ID_AUDITORIA

