--MIG_CAPTURE_BILL_BAL_MAINTEN_D
--12,217


WITH CTE AS(
--10,401
SELECT DISTINCT BILL.ARRANGEMENT, CASE WHEN BILL.ARRANGEMENT = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR))
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END ARRANGEMENT_AUDITORIA,
BILL.BILL_DATE, CASE WHEN BILL.BILL_DATE = CONVERT(VARCHAR(MAX),CAFYM.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CADFYM)),2)
THEN CONVERT(VARCHAR(MAX),CAFYM.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CADFYM)),2)
END BILL_DATE_AUDITORIA,
BILL.PAYMENT_DATE,  CASE WHEN BILL.BILL_DATE = CONVERT(VARCHAR(MAX),CAFYM.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CADFYM)),2)
THEN CONVERT(VARCHAR(MAX),CAFYM.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CADFYM)),2)
END PAYMENT_DATE_AUDITORIA,
BILL.PROPERTY,
CASE WHEN BILL.PROPERTY = 'ACCOUNT' THEN 'ACCOUNT'
ELSE 'PRINCIPALINT' END PROPERTY_AUDITORIA,
BILL.NEW_PROP_AMT, 
CASE WHEN BILL.NEW_PROP_AMT = CAFYM.CAVFYM - CAFYM.CAPFYM THEN CAFYM.CAVFYM - CAFYM.CAPFYM 
WHEN BILL.NEW_PROP_AMT =  CAFYM.CACNIN - CAFYM.CATORT THEN CAFYM.CACNIN - CAFYM.CATORT
END NEW_PROP_AMT_AUDITORIA
FROM MIG_CAPTURE_BILL_BAL_MAINTEN_D BILL
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(RIGHT(BILL.ARRANGEMENT,7))) = RTRIM(LTRIM(CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAAFYM,CAMFYM,CADFYM,CAVFYM,CACNIN,CAPFYM,CATORT FROM CAFYMDIS) CAFYM  
ON RTRIM(LTRIM(CAFYM.CANUCR))=RTRIM(LTRIM(CREDIT.CANUCR))
AND BILL.BILL_DATE = CONVERT(VARCHAR(MAX),CAFYM.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYM.CADFYM)),2)
AND BILL.PROPERTY =
CASE WHEN BILL.PROPERTY = 'ACCOUNT' THEN 'ACCOUNT'
ELSE 'PRINCIPALINT' END
AND BILL.NEW_PROP_AMT = 
CASE WHEN BILL.NEW_PROP_AMT = CAFYM.CAVFYM - CAFYM.CAPFYM THEN CAFYM.CAVFYM - CAFYM.CAPFYM 
WHEN BILL.NEW_PROP_AMT =  CAFYM.CACNIN - CAFYM.CATORT THEN CAFYM.CACNIN - CAFYM.CATORT
END
WHERE BILL.PAYMENT_TYPE IN ('CONSTANT' ,'LINEAR' ,'CONSTANT','INTEREST')

UNION ALL
--1,816
SELECT distinct RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) ARRANGEMENT , CASE WHEN MAINTEN.ARRANGEMENT = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR))
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END ARRANGEMENT_AUDITORIA,
MAINTEN.BILL_DATE, CASE WHEN MAINTEN.BILL_DATE =  CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) END AS BILL_DATE_AUDITORIA,
MAINTEN.PAYMENT_DATE, CASE WHEN MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
		END AS PAYMENT_DATE_AUDITORIA,
		MAINTEN.PROPERTY , PAY_TY.PROPERTY PROPERTY_AUDITORIA,
  MAINTEN.NEW_PROP_AMT,	CASE 
		WHEN MAINTEN.NEW_PROP_AMT = CAFYCO.CAVFYM - CAFYCO.CAPFYM THEN CAFYCO.CAVFYM - CAFYCO.CAPFYM
		END AS NEW_PROP_AMT_AUDITORIA
FROM MIG_CAPTURE_BILL_BAL_MAINTEN_D MAINTEN
LEFT JOIN CACREDIT CREDIT ON RTRIM(LTRIM(RIGHT(MAINTEN.ARRANGEMENT,7))) = RTRIM(LTRIM(CREDIT.CANUCR))
left JOIN (SELECT DISTINCT CAAFYM,CAMFYM,CADFYM,CANUCR,CACORR,CAVFYM,CAPFYM FROM CAFYMCOB) CAFYCO ON RTRIM(LTRIM(RIGHT(MAINTEN.ARRANGEMENT,7))) = RTRIM(LTRIM(CAFYCO.CANUCR))
AND MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
AND MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
AND MAINTEN.NEW_PROP_AMT = CAFYCO.CAVFYM - CAFYCO.CAPFYM
 left  join (
    select  PROPERTY
    from MIG_HOM_PAYMENT_TYPE_CARGOS_CB
  ) PAY_TY ON MAINTEN.PROPERTY = PAY_TY.PROPERTY
WHERE MAINTEN.PAYMENT_TYPE NOT IN ('CONSTANT' ,'LINEAR' ,'CONSTANT','INTEREST')
)

----ARRANGEMENT VS ARRANGEMENT_AUDITORIA
--SELECT ARRANGEMENT , ARRANGEMENT_AUDITORIA FROM CTE
--WHERE ARRANGEMENT <> ARRANGEMENT_AUDITORIA



----BILL_DATE VS BILL_DATE_AUDITORIA
--SELECT BILL_DATE , BILL_DATE_AUDITORIA FROM CTE
--WHERE BILL_DATE <> BILL_DATE_AUDITORIA


----PAYMENT_DATE VS PAYMENT_DATE_AUDITORIA
--SELECT PAYMENT_DATE , PAYMENT_DATE_AUDITORIA FROM CTE
--WHERE PAYMENT_DATE <> PAYMENT_DATE_AUDITORIA


----PROPERTY VS PROPERTY_AUDITORIA
--SELECT PROPERTY , PROPERTY_AUDITORIA FROM CTE
--WHERE PROPERTY <> PROPERTY_AUDITORIA


----NEW_PROP_AMT VS NEW_PROP_AMT_AUDITORIA
--SELECT NEW_PROP_AMT , NEW_PROP_AMT_AUDITORIA FROM CTE
--WHERE NEW_PROP_AMT <> NEW_PROP_AMT_AUDITORIA