--MIG_TAKE_OVER_D_LIMIT
--84


WITH CTE AS(
SELECT DISTINCT RTRIM(LTRIM(MIT.K_KEY)) K_KEY, CASE WHEN MIT.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
MIT.LIMIT_REFERENCE, CASE WHEN MIT.LIMIT_REFERENCE = CCGB.LIMIT_PRODUCT THEN CCGB.LIMIT_PRODUCT ELSE CUPS.LIMITE_SUBPRODUCTO
END LIMIT_REFERENCE_AUDITORIA,
MIT.LIMIT_SERIAL, CASE WHEN MIT.LIMIT_SERIAL = CCGB.SERIAL_NUMBER THEN CCGB.SERIAL_NUMBER ELSE 1
END LIMIT_SERIAL_AUDITORIA
FROM MIG_TAKE_OVER_D_LIMIT MIT
left JOIN (SELECT  CANUCR,DSCORR FROM CADISCAP) DISCAP2
ON RTRIM(LTRIM(RIGHT(MIT.K_KEY,7))) = RTRIM(LTRIM(DISCAP2.CANUCR))
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(RIGHT(MIT.K_KEY,7))) = RTRIM(LTRIM(CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT PRESTAMO, LIMITE, SECUENCIA FROM MIG_HOM_LIMIT_HELP_CONTRATO_TO) CONT2
ON  RTRIM(LTRIM(CONT2.PRESTAMO)) = RTRIM(LTRIM(CREDIT.CANUCR))
AND MIT.LIMIT_REFERENCE = CONT2.LIMITE
LEFT JOIN MIG_HOM_CUPOS CUPS
ON MIT.LIMIT_REFERENCE = CUPS.LIMITE_SUBPRODUCTO
LEFT JOIN(
SELECT 
        PRODUCTO,
        LIMIT_PRODUCT,
        SERIAL_NUMBER
    FROM KIM_ESP_REL_PRODUCTO_PROPIEDAD RPP
    INNER JOIN KIM_ESP_RELACION_GARANTIA_PROP RGP
    ON RPP.NUMERO_DE_PROPIEDAD = RGP.ID_PROPIEDAD_RGP
    INNER JOIN KIM_CONTRATO_2 KC2
    ON RGP.ID_GARANTIA_RGP = KC2.ID_GARANTIA_RGP
    INNER JOIN mig_limit_contrato CONT
    ON KC2.ID_CTR = SUBSTRING(CONT.NUMERO_CONTRATO,10,(LEN(CONT.NUMERO_CONTRATO)-9))
    WHERE KC2.CONDICION_CONTRATO_CGB <> 'Retirado'
)CCGB
ON CCGB.PRODUCTO = TRIM(CREDIT.CANUCR) 
AND MIT.LIMIT_REFERENCE = CASE WHEN MIT.LIMIT_REFERENCE = CCGB.LIMIT_PRODUCT THEN CCGB.LIMIT_PRODUCT ELSE CUPS.LIMITE_SUBPRODUCTO
END)

--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY<>K_KEY_AUDITORIA


--SELECT LIMIT_REFERENCE,LIMIT_REFERENCE_AUDITORIA FROM CTE
--WHERE LIMIT_REFERENCE<>LIMIT_REFERENCE_AUDITORIA

--SELECT LIMIT_SERIAL, LIMIT_SERIAL_AUDITORIA FROM CTE
--WHERE LIMIT_SERIAL <> LIMIT_SERIAL_AUDITORIA