--MIG_TAKE_OVER_D_PRINCIPALINT
--10,624

WITH CTE AS(
SELECT  RTRIM(LTRIM(OVER_D.K_KEY))K_KEY , RTRIM(LTRIM('L'+CASE WHEN DISCAP2.DSCORR = 1 THEN 'A' WHEN DISCAP2.DSCORR = 2 THEN 'B' END+CREDIT.CANUCR))K_KEY_AUDITORIA,
OVER_D.FIXED_RATE, CASE WHEN CAPROD.PRTFOV = 'F' THEN CREDIT.CATAV1 END  FIXED_RATE_AUDITORIA,
OVER_D.MARGIN_RATE, CAST(ABS(CREDIT.CATAV1-CREDIT.CRTSRE)AS NUMERIC(18,2)) MARGIN_RATE_AUDITORIA,
CAST(OVER_D.PERIODIC_RATE AS NUMERIC(18,2))PERIODIC_RATE, CAST(CREDIT.CRTSRE AS NUMERIC(18,2)) PERIODIC_RATE_AUDITORIA,
CAST(OVER_D.INITIAL_RESET_DATE AS INT)INITIAL_RESET_DATE,  
CASE CACSTC
WHEN 40 
THEN FORMAT(DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS),'yyyyMMdd')
ELSE
CASE 
WHEN DATEDIFF(DAY,DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS),DATEFROMPARTS (DSAVCP,DSMVCP,DSDVCP)) >= 90
THEN '20210518'
ELSE
FORMAT(DATEADD(DAY,90,DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS)),'yyyyMMdd')
END
END AS  INITIAL_RESET_DATE_AUDITORIA
FROM MIG_TAKE_OVER_D_PRINCIPALINT OVER_D
left JOIN (SELECT  CANUCR,DSAVCP,DSMVCP,DSDVCP,DSCORR FROM CADISCAP) DISCAP2
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) = RTRIM(LTRIM(DISCAP2.CANUCR))
left JOIN (SELECT  CANUCR,CATAV1,CRTSRE,CACSTC,CRARTS,CRMRTS,CRDRTS,CAPROD,CASUBP FROM CACREDIT) CREDIT
ON  RTRIM(LTRIM(OVER_D.K_KEY)) = RTRIM(LTRIM('L'+CASE WHEN DISCAP2.DSCORR = 1 THEN 'A' WHEN DISCAP2.DSCORR = 2 THEN 'B' END+CREDIT.CANUCR))
AND OVER_D.MARGIN_RATE = CAST(ABS(CREDIT.CATAV1-CREDIT.CRTSRE)AS NUMERIC(18,2)) 
AND CAST(OVER_D.PERIODIC_RATE AS NUMERIC(18,2))= CAST(CREDIT.CRTSRE AS NUMERIC(18,2)) 
left JOIN (select distinct TIPPRO,SUBPRO,PRTFOV from CAPRODUC) CAPROD
ON CREDIT.CAPROD = CAPROD.TIPPRO
AND CREDIT.CASUBP = CAPROD.SUBPRO
AND OVER_D.FIXED_RATE = CASE WHEN CAPROD.PRTFOV = 'F' THEN CREDIT.CATAV1 END  
where RTRIM(LTRIM('L'+CASE WHEN DISCAP2.DSCORR = 1 THEN 'A' WHEN DISCAP2.DSCORR = 2 THEN 'B' END+CREDIT.CANUCR)) is not null
--ORDER BY RTRIM(LTRIM('L'+CASE WHEN DISCAP2.DSCORR = 1 THEN 'A' WHEN DISCAP2.DSCORR = 2 THEN 'B' END+CREDIT.CANUCR))
--AND RTRIM(LTRIM(OVER_D.K_KEY)) IN('LB3337528',
--'LA3337528')
)


--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY<>K_KEY_AUDITORIA


--SELECT FIXED_RATE,FIXED_RATE_AUDITORIA FROM CTE
--WHERE FIXED_RATE<>FIXED_RATE_AUDITORIA


--SELECT MARGIN_RATE,MARGIN_RATE_AUDITORIA FROM CTE
--WHERE MARGIN_RATE<>MARGIN_RATE_AUDITORIA


--SELECT PERIODIC_RATE,PERIODIC_RATE_AUDITORIA FROM CTE
--WHERE PERIODIC_RATE<>PERIODIC_RATE_AUDITORIA


--SELECT K_KEY,INITIAL_RESET_DATE,INITIAL_RESET_DATE_AUDITORIA FROM CTE
--WHERE INITIAL_RESET_DATE<>INITIAL_RESET_DATE_AUDITORIA
--AND RTRIM(LTRIM(K_KEY)) IN('LB3337528','LA3337528')



--SCRIPT PARA VERIFICAR EL CAMPO INITIAL_RESET_DATE
--El resultado que debe de arrojar para este prestamo tiene que ser 20220215

--SELECT CREDIT.CANUCR, DISCAP2.CANUCR, 
--CASE CACSTC
--WHEN 40 
--THEN FORMAT(DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS),'yyyyMMdd')
--ELSE
--CASE 
--WHEN DATEDIFF(DAY,DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS),DATEFROMPARTS (DSAVCP,DSMVCP,DSDVCP)) >= 90
--THEN '20210518'
--ELSE
--FORMAT(DATEADD(DAY,90,DATEFROMPARTS(CREDIT.CRARTS,CREDIT.CRMRTS,CREDIT.CRDRTS)),'yyyyMMdd')
--END
--END AS INITIAL_RESET_DATE
--FROM CADISCAP DISCAP2
--LEFT JOIN CACREDIT CREDIT
--ON RTRIM(LTRIM(DISCAP2.CANUCR)) = RTRIM(LTRIM(CREDIT.CANUCR)) 
--WHERE CREDIT.CANUCR = '3337528'