-- MIG_TAKE_OVER_D
-- TOTAL 9,332

--WITH CTE AS(
SELECT  RTRIM(LTRIM(OVER_D.K_KEY))K_KEY , CASE WHEN OVER_D.K_KEY = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
ELSE RTRIM(LTRIM('LB'+CREDIT.CANUCR)) END K_KEY_AUDITORIA,
OVER_D.UPLOAD_COMPANY , E.COMPANY UPLOAD_COMPANY_AUDITORIA,
REPLACE(OVER_D.CUSTOMER ,'::','')CUSTOMER, REPLACE(X.CUSTOMER,'::','') AS CUSTOMER_AUDITORIA,
OVER_D.CUSTOMER_ROLE, CASE
WHEN X.CUSTOMER_ROLE = '::OWNER' THEN 'OWNER'
WHEN X.CUSTOMER_ROLE = '::OWNER::JOINT.OWNER' THEN 'OWNER::JOINT.OWNER'
END  CUSTOMER_ROLE_AUDITORIA,
OVER_D.CURRENCY, 
CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
WHEN CREDIT.PRMONE = 034 THEN 'USD'
WHEN CREDIT.PRMONE IN (035,004) THEN 'EUR' END AS CURRENCY_AUDITORIA,
OVER_D.ORIG_CONTRACT_DATE,
CONVERT(VARCHAR(MAX),CREDIT.CAACOC)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAMCOC)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CADCOC)),2) AS ORIG_CONTRACT_DATE_AUDITORIA
FROM MIG_TAKE_OVER_D OVER_D
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) = RTRIM(LTRIM(CREDIT.CANUCR)) 
LEFT JOIN TAKE_OVER_D_HELP_CUSTOMERS X
ON RTRIM(LTRIM(RIGHT(OVER_D.K_KEY,7))) = RTRIM(LTRIM(X.CANUCR)) 
LEFT JOIN (SELECT DISTINCT COMPANY FROM MIG_HOM_SUCURSAL) E
ON  OVER_D.UPLOAD_COMPANY = E.COMPANY
--WHERE RIGHT(OVER_D.K_KEY,7) = '2830765'
--)

--SELECT K_KEY, K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY <> K_KEY_AUDITORIA


--SELECT UPLOAD_COMPANY, UPLOAD_COMPANY_AUDITORIA FROM CTE
--WHERE UPLOAD_COMPANY <> UPLOAD_COMPANY_AUDITORIA



--SELECT CUSTOMER, CUSTOMER_AUDITORIA FROM CTE
--WHERE CUSTOMER <> CUSTOMER_AUDITORIA


--SELECT CUSTOMER_ROLE, CUSTOMER_ROLE_AUDITORIA FROM CTE
--WHERE CUSTOMER_ROLE <> CUSTOMER_ROLE_AUDITORIA


--SELECT CURRENCY, CURRENCY_AUDITORIA FROM CTE
--WHERE CURRENCY <> CURRENCY_AUDITORIA


--SELECT ORIG_CONTRACT_DATE, ORIG_CONTRACT_DATE_AUDITORIA FROM CTE
--WHERE ORIG_CONTRACT_DATE <> ORIG_CONTRACT_DATE_AUDITORIA







