--CAPTURE BILL PROPERTY
--1,536,140
--CAPITAL,INTERES

WITH CTE AS(
SELECT RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) ARRANGEMENT , RTRIM(LTRIM('L'+CREDIT.CANUCR)) ARRANGEMENT_AUDITORIA,
MAINTEN.BILL_DATE ,CASE WHEN MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) END AS BILL_DATE_AUDITORIA,
MAINTEN.PAYMENT_DATE , CASE WHEN MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) END AS PAYMENT_DATE_AUDITORIA,
MAINTEN.PROPERTY,CASE WHEN  PAG.CAVFYM > 0 AND PAG.CACNIN > 0 THEN 'ACCOUNT'
					  WHEN PAG.CAVFYM > 0 AND PAG.CACNIN = 0 THEN 'ACCOUNT' ELSE 'ACCOUNT'
					  END AS PROPERTY_AUDITORIA,
MAINTEN.NEW_PROP_AMT,
	CASE 
		WHEN MAINTEN.NEW_PROP_AMT = PAG.CAVFYM - PAG.CAPFYM THEN PAG.CAVFYM - PAG.CAPFYM 
		WHEN MAINTEN.NEW_PROP_AMT = PAG.CACNIN - PAG.CATORT THEN PAG.CACNIN - PAG.CATORT
	END AS NEW_PROP_AMT_AUDITORIA
FROM MIG_CAPTURE_BILL_BAL_MAINTEN MAINTEN
LEFT JOIN CACREDIT CREDIT ON RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN CAFYMPAG PAG ON  RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+PAG.CANUCR))
AND MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2)
WHERE PAYMENT_TYPE IN('CONSTANT','LINEAR')
AND MAINTEN.PROPERTY = 'ACCOUNT'
UNION ALL
SELECT DISTINCT RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) ARRANGEMENT , RTRIM(LTRIM('L'+CREDIT.CANUCR)) ARRANGEMENT_AUDITORIA,
MAINTEN.BILL_DATE ,CASE WHEN MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) END AS BILL_DATE_AUDITORIA,
MAINTEN.PAYMENT_DATE , CASE WHEN MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2) END AS PAYMENT_DATE_AUDITORIA,
MAINTEN.PROPERTY,CASE WHEN  PAG.CAVFYM > 0 AND PAG.CACNIN > 0 THEN 'PRINCIPALINT'
					  WHEN PAG.CAVFYM = 0 AND PAG.CACNIN > 0 THEN 'PRINCIPALINT' 
					  END AS PROPERTY_AUDITORIA,
MAINTEN.NEW_PROP_AMT,
	CASE 
		WHEN MAINTEN.NEW_PROP_AMT = PAG.CAVFYM - PAG.CAPFYM THEN PAG.CAVFYM - PAG.CAPFYM 
		WHEN MAINTEN.NEW_PROP_AMT = PAG.CACNIN - PAG.CATORT THEN PAG.CACNIN - PAG.CATORT
	END AS NEW_PROP_AMT_AUDITORIA
FROM MIG_CAPTURE_BILL_BAL_MAINTEN MAINTEN
LEFT JOIN CACREDIT CREDIT ON RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN CAFYMPAG PAG ON  RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+PAG.CANUCR))
AND MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),PAG.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADFYM)),2)
WHERE PAYMENT_TYPE IN('CONSTANT','INTEREST')
AND MAINTEN.PROPERTY = 'PRINCIPALINT'
UNION ALL
--CARGOS
SELECT distinct RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) ARRANGEMENT , RTRIM(LTRIM('L'+CREDIT.CANUCR)) ARRANGEMENT_AUDITORIA,
MAINTEN.BILL_DATE, CASE WHEN MAINTEN.BILL_DATE =  CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) END AS BILL_DATE_AUDITORIA,
MAINTEN.PAYMENT_DATE, CASE WHEN MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2) THEN CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
		END AS PAYMENT_DATE_AUDITORIA,
		MAINTEN.PROPERTY , PAY_TY.PROPERTY PROPERTY_AUDITORIA,
  MAINTEN.NEW_PROP_AMT,	CASE 
		WHEN MAINTEN.NEW_PROP_AMT = CAFYCO.CAVFYM - CAFYCO.CAPFYM THEN CAFYCO.CAVFYM - CAFYCO.CAPFYM
		END AS NEW_PROP_AMT_AUDITORIA
FROM MIG_CAPTURE_BILL_BAL_MAINTEN MAINTEN
LEFT JOIN CACREDIT CREDIT ON RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
left JOIN (SELECT DISTINCT CAAFYM,CAMFYM,CADFYM,CANUCR,CACORR,CAVFYM,CAPFYM FROM CAFYMCOB) CAFYCO ON RTRIM(LTRIM(MAINTEN.ARRANGEMENT)) = RTRIM(LTRIM('L'+CAFYCO.CANUCR))
AND MAINTEN.BILL_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
AND MAINTEN.PAYMENT_DATE = CONVERT(VARCHAR(MAX),CAFYCO.CAAFYM)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CAMFYM)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAFYCO.CADFYM)),2)
AND MAINTEN.NEW_PROP_AMT = CAFYCO.CAVFYM - CAFYCO.CAPFYM
 left  join (
    select  PROPERTY
    from MIG_HOM_PAYMENT_TYPE_CARGOS_CB
  ) PAY_TY ON MAINTEN.PROPERTY = PAY_TY.PROPERTY
WHERE MAINTEN.PAYMENT_TYPE not in ('CONSTANT','LINEAR','INTEREST')
)

--SELECT COUNT(*) FROM CTE

----ARRANGEMENT VS ARRANGEMENT_AUDITORIA
--SELECT ARRANGEMENT , ARRANGEMENT_AUDITORIA FROM CTE
--WHERE ARRANGEMENT <> ARRANGEMENT_AUDITORIA



----BILL_DATE VS BILL_DATE_AUDITORIA
--SELECT BILL_DATE , BILL_DATE_AUDITORIA FROM CTE
--WHERE BILL_DATE <> BILL_DATE_AUDITORIA


----PAYMENT_DATE VS PAYMENT_DATE_AUDITORIA
--SELECT PAYMENT_DATE , PAYMENT_DATE_AUDITORIA FROM CTE
--WHERE PAYMENT_DATE <> PAYMENT_DATE_AUDITORIA


----PROPERTY VS PROPERTY_AUDITORIA
--SELECT PROPERTY , PROPERTY_AUDITORIA FROM CTE
--WHERE PROPERTY <> PROPERTY_AUDITORIA


----NEW_PROP_AMT VS NEW_PROP_AMT_AUDITORIA
--SELECT NEW_PROP_AMT , NEW_PROP_AMT_AUDITORIA FROM CTE
--WHERE NEW_PROP_AMT <> NEW_PROP_AMT_AUDITORIA



