--CAPTURE BALANCE,
--199,398 TOTAL

WITH CTE AS(
SELECT DISTINCT
BALANCE.K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
BALANCE.UPLOAD_COMPANY, SUC.COMPANY AS UPLOAD_COMPANY_AUDITORIA,
BALANCE.PRODUCT ,ISNULL(PROD7X.PRODUCT,PROD.PRODUCT) PRODUCT_AUDITORIA
FROM MIG_CAPTURE_BALANCE BALANCE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(BALANCE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN MIG_HOM_SUCURSAL SUC
ON CREDIT.CAAGEN = SUC.CODIGO
LEFT JOIN MIG_HOM_PRODUCT PROD
ON CREDIT.CAPROD = PROD.CAPROD
AND CREDIT.CASUBP = PROD.CASUBP
AND PROD.PLANTILLA = 'S'
LEFT JOIN (SELECT DISTINCT CODTAB, SW02,CODELE FROM ACTAB1) TAB1
ON TAB1.CODTAB = 'K7'
AND CREDIT.CAPROD = 1
AND CREDIT.CASUBP IN (70,71)
AND TRIM(CREDIT.AXASER) = TRIM(TAB1.CODELE)
LEFT JOIN MIG_HOM_PRODUCT_70_71 PROD7X
ON CREDIT.CAPROD = PROD7X.CAPROD
AND CREDIT.CASUBP = PROD7X.CASUBP
AND ISNULL(TRIM(TAB1.SW02),'P') = TRIM(PROD7X.SW02)
)

----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY, K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY <> K_KEY_AUDITORIA


----UPLOAD_COMPANY VS UPLOAD_COMPANY_AUDITORIA
--SELECT UPLOAD_COMPANY, UPLOAD_COMPANY_AUDITORIA FROM CTE
--WHERE UPLOAD_COMPANY <> UPLOAD_COMPANY_AUDITORIA


----PRODUCT VS UPLOAD_COMPANY_AUDITORIA
--SELECT PRODUCT, PRODUCT_AUDITORIA FROM CTE
--WHERE PRODUCT <> PRODUCT_AUDITORIA
