--CAPTURE-BALANCE PROPERTY
--398,796 TOTAL

WITH CTE AS(
SELECT 
K_KEY,
K_KEY_AUDITORIA,
CASE WHEN NEW_BAL_AMT = 0 THEN NULL ELSE NEW_BAL_AMT END AS NEW_BAL_AMT,
NEW_BAL_AMT_AUDITORIA
FROM(
SELECT 
	MAIN.K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
	--MAIN.ADJUST_PROP,
	--MAIN.ADJ_BAL_TYPE,
	MAIN.NEW_BAL_AMT,  (CASE
    WHEN abs((CAST(CREDIT.CACAVI AS NUMERIC(13,2)) - CAST(CREDIT.CAATRA AS NUMERIC(13,2)))) = 0 THEN 1
    ELSE abs((CAST(CREDIT.CACAVI AS NUMERIC(13,2)) - CAST(CREDIT.CAATRA AS NUMERIC(13,2))))
  END * -1) NEW_BAL_AMT_AUDITORIA
FROM MIG_CAPTURE_BAL_MAINTENANCE MAIN
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(MAIN.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR)) 
WHERE MAIN.ADJUST_PROP = 'ACCOUNT' AND MAIN.ADJ_BAL_TYPE = 'CURACCOUNT'
--AND K_KEY = 'L0119004'
UNION ALL
SELECT 
	MAIN.K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR)) ,
	--MAIN.ADJUST_PROP,
	--MAIN.ADJ_BAL_TYPE,
	MAIN.NEW_BAL_AMT, (CAST(ROUND(CAINME,2,1) AS DECIMAL(18,2))) * -1  NEW_BAL_AMT_AUDITORIA
FROM MIG_CAPTURE_BAL_MAINTENANCE MAIN
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(MAIN.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR)) 
WHERE MAIN.ADJUST_PROP = 'PRINCIPALINT' AND MAIN.ADJ_BAL_TYPE = 'ACCPRINCIPALINT'
--AND K_KEY = 'L0119004'
--ORDER BY MAIN.K_KEY
)X
)
----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY , K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY <> K_KEY_AUDITORIA

----NEW_BAL_AMT VS NEW_BAL_AMT_AUDITORIA
--SELECT K_KEY,NEW_BAL_AMT , NEW_BAL_AMT_AUDITORIA FROM CTE
--WHERE NEW_BAL_AMT <> NEW_BAL_AMT_AUDITORIA