--MIG_TAKE_OVER_PRINCIPALINT
--TOTAL 213,933


WITH CTE AS
(
SELECT RTRIM(LTRIM(LINT.K_KEY))K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
LINT.FIXED_RATE, CASE WHEN CAPROD.PRTFOV = 'F' THEN CREDIT.CATAV1 END  FIXED_RATE_AUDITORIA,
LINT.MARGIN_RATE, abs(CREDIT.CATAV1-CREDIT.CRTSRE) MARGIN_RATE_AUDITORIA,
LINT.PERIODIC_RATE,CREDIT.CRTSRE PERIODIC_RATE_AUDITORIA,
LINT.INITIAL_RESET_DATE, 
CASE
	WHEN
CONVERT(VARCHAR(MAX),CREDIT.CRARTS)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMRTS)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDRTS)),2) 
<= 20211025 THEN '20211025'
ELSE CONVERT(VARCHAR(MAX),CREDIT.CRARTS)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMRTS)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDRTS)),2) 
END AS
INITIAL_RESET_DATE_AUDITORIA
FROM MIG_TAKE_OVER_PRINCIPALINT LINT
LEFT JOIN CACREDIT CREDIT ON RTRIM(LTRIM(LINT.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN CAPRODUC CAPROD
ON LINT.CAPROD = CAPROD.TIPPRO
AND LINT.CASUBP = CAPROD.SUBPRO
)

----TOTAL DE LA TABLA QUE SE IMPORTO
--select COUNT(*) from cte


----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY, K_KEY_AUDITORIA FROM CTE
--WHERE K_KEY <> K_KEY_AUDITORIA

----FIXED_RATE VS FIXED_RATE_AUDITORIA
--SELECT FIXED_RATE, FIXED_RATE_AUDITORIA FROM CTE
--WHERE FIXED_RATE <> FIXED_RATE_AUDITORIA


----MARGIN_RATE VS MARGIN_RATE_AUDITORIA
--SELECT MARGIN_RATE, MARGIN_RATE_AUDITORIA FROM CTE
--WHERE MARGIN_RATE <> MARGIN_RATE_AUDITORIA

----PERIODIC_RATE VS PERIODIC_RATE_AUDITORIA
--SELECT PERIODIC_RATE, PERIODIC_RATE_AUDITORIA FROM CTE
--WHERE PERIODIC_RATE <> PERIODIC_RATE_AUDITORIA

----INITIAL_RESET_DATE VS INITIAL_RESET_DATE_AUDITORIA
--SELECT K_KEY, INITIAL_RESET_DATE, INITIAL_RESET_DATE_AUDITORIA FROM CTE
--WHERE INITIAL_RESET_DATE <> INITIAL_RESET_DATE_AUDITORIA