 --MIG_TAKE_OVER_SCHEDULE
 --TOTAL 354,756


 --354,756
--WITH CTE AS(
--252,467
SELECT 
RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.ACTUAL_AMT,CASE WHEN DULE.ACTUAL_AMT = PAG.CAVACP THEN PAG.CAVACP
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END  ACTUAL_AMT_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAVACP FROM CACOMPAG) PAG 
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+PAG.CANUCR))
AND DULE.ACTUAL_AMT = CASE WHEN PAG.CAVACP = 0 THEN NULL ELSE PAG.CAVACP END
WHERE DULE.TIPO = 'CAP'
UNION ALL
--1,423
--TABLA CACOMTRX
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.ACTUAL_AMT,CASE WHEN DULE.ACTUAL_AMT = PAG.CAVACP THEN PAG.CAVACP
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END  ACTUAL_AMT_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAVACP FROM CACOMTRX) PAG
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
AND DULE.ACTUAL_AMT = CASE WHEN PAG.CAVACP = 0 THEN NULL ELSE PAG.CAVACP END
WHERE DULE.TIPO = 'CAP2'
UNION ALL
--9
--TABLA CACOMTRX
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.ACTUAL_AMT,CASE WHEN DULE.ACTUAL_AMT = PAG.CAVACP THEN PAG.CAVACP
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END  ACTUAL_AMT_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAVACP FROM CACOMTRX) PAG
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
AND DULE.ACTUAL_AMT = CASE WHEN PAG.CAVACP = 0 THEN NULL ELSE PAG.CAVACP END
WHERE DULE.TIPO = 'CAP3'
UNION ALL
--67
--TABLA CACOMDIS
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.ACTUAL_AMT,CASE WHEN DULE.ACTUAL_AMT = COMDIS.CDVACP THEN COMDIS.CDVACP
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END  ACTUAL_AMT_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CDVACP FROM CACOMDIS) COMDIS
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(COMDIS.CANUCR))
AND DULE.ACTUAL_AMT = CASE WHEN COMDIS.CDVACP = 0 THEN NULL ELSE COMDIS.CDVACP END
WHERE DULE.TIPO = 'CAP4'
UNION ALL
--100,790
--TABLA CACOBADI
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.ACTUAL_AMT,  CASE WHEN DULE.ACTUAL_AMT = BADI.CAMFRE THEN BADI.CAMFRE
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END ACTUAL_AMT_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAMFRE FROM CACOBADI) BADI
ON  RTRIM(LTRIM(RIGHT(DULE.K_KEY,7))) = RTRIM(LTRIM(BADI.CANUCR))
AND DULE.ACTUAL_AMT =  CASE WHEN DULE.ACTUAL_AMT = BADI.CAMFRE THEN BADI.CAMFRE
WHEN DULE.ACTUAL_AMT = 1 THEN 1 ELSE NULL END
WHERE DULE.TIPO = 'INT'--)

-- SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE  K_KEY <> K_KEY_AUDITORIA                                                    


--SELECT ACTUAL_AMT,ACTUAL_AMT_AUDITORIA FROM CTE 
--WHERE  ACTUAL_AMT <> ACTUAL_AMT_AUDITORIA

-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------
--WITH CTE2 as(
SELECT  RTRIM(LTRIM(DULE.K_KEY))K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR))K_KEY_AUDITORIA,
DULE.START_DATE,CASE WHEN DULE.START_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
then CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHEN DULE.START_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY' ELSE NULL end START_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT 
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
left JOIN (select distinct CANUCR,CAMECP, CAANCP,CADICP from CACOMPAG) PAG 
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
and DULE.START_DATE =  CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHERE DULE.TIPO = 'CAP'
UNION ALL
--1,669
--TABLA CACOMTRX
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE,CASE WHEN DULE.START_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
then CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHEN DULE.START_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY' ELSE NULL end START_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAANCP,CAMECP,CADICP FROM CACOMTRX) PAG
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
AND DULE.START_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHERE DULE.TIPO = 'CAP2'
UNION ALL
--8
--TABLA CACOMTRX
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE,CASE WHEN DULE.START_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
then CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHEN DULE.START_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY' ELSE NULL end START_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAANCP,CAMECP,CADICP FROM CACOMTRX) PAG
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
AND DULE.START_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
WHERE DULE.TIPO = 'CAP3'
--170
--TABLA CACOMDIS
UNION ALL
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE,CASE WHEN DULE.START_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2)
then CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2)
WHEN DULE.START_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY' ELSE NULL end START_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CDANCP,CDMECP,CDDICP FROM CACOMDIS) COMDIS
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(COMDIS.CANUCR))
AND DULE.START_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2)
WHERE DULE.TIPO = 'CAP4'
UNION ALL
--117,683
--TABLA CACOMDIS
SELECT  RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE, CASE WHEN DULE.START_DATE = CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2)
then CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2)
WHEN DULE.START_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY' ELSE NULL end START_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAASRE,CAMSRE,CADSRE FROM CACOBADI) BADI
ON  RTRIM(LTRIM(RIGHT(DULE.K_KEY,7))) = RTRIM(LTRIM(BADI.CANUCR))
AND DULE.START_DATE =  CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2)
WHERE DULE.TIPO = 'INT'
--)
--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE2 
--WHERE  K_KEY <> K_KEY_AUDITORIA

--SELECT START_DATE,START_DATE_AUDITORIA FROM CTE2 
--WHERE  START_DATE <> START_DATE_AUDITORIA

/*************************************************************************************************/
WITH CTE3 AS(
SELECT  
    X.K_KEY,
    K_KEY_AUDITORIA,
	X.END_DATE,
    --CASE WHEN X.CACFRE != 7 THEN X.END_DATE ELSE CASE WHEN START_DATE NOT BETWEEN '20210302' AND STG_MIGT24.FN_GET_PARAMETERS_VALUE('MIGRATION_DATE') THEN TO_CHAR(TO_DATE(STG_MIGT24.FN_GET_PARAMETERS_VALUE('MIGRATION_DATE'),'YYYYMMDD')+1,'YYYYMMDD') ELSE X.END_DATE END END AS END_DATE
    CASE 
        WHEN ( X.END_DATE < '20211025' )
        THEN 
            X.START_DATE
        ELSE 
            CASE WHEN X.START_DATE > X.END_DATE THEN X.START_DATE ELSE X.END_DATE END
    END 
    AS END_DATE_AUDITORIA
FROM(
SELECT  RTRIM(LTRIM(DULE.K_KEY))K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR))K_KEY_AUDITORIA,
DULE.START_DATE,DULE.END_DATE, CASE WHEN DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2) then  CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
ELSE 
CASE when DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2) then CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
ELSE 
CASE WHEN DULE.END_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY'
END END END  END_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT 
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
left JOIN (select DISTINCT CANUCR,CAMECP, CAANCP,CADICP,COMANO,COMMES,COMDIA from CACOMPAG) PAG 
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
WHERE DULE.TIPO = 'CAP'
UNION ALL
SELECT  RTRIM(LTRIM(DULE.K_KEY))K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR))K_KEY_AUDITORIA,
DULE.START_DATE,DULE.END_DATE, CASE WHEN DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2) then  CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
ELSE 
CASE when DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2) then CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
ELSE 
CASE WHEN DULE.END_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY'
END END END  END_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT 
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
left JOIN (select DISTINCT CANUCR,CAMECP, CAANCP,CADICP,COMANO,COMMES,COMDIA from CACOMTRX) PAG 
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
WHERE DULE.TIPO = 'CAP2'
UNION ALL
--8
--TABLA CACOMTRX
SELECT  RTRIM(LTRIM(DULE.K_KEY))K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR))K_KEY_AUDITORIA,
DULE.START_DATE,DULE.END_DATE, CASE WHEN DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2) then  CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
ELSE 
CASE when DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2) then CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
ELSE 
CASE WHEN DULE.END_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY'
END END END  END_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT 
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
left JOIN (select DISTINCT CANUCR,CAMECP, CAANCP,CADICP,COMANO,COMMES,COMDIA from CACOMTRX) PAG 
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(PAG.CANUCR))
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.CAANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CAMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.CADICP)),2)
and DULE.END_DATE = CONVERT(VARCHAR(MAX),PAG.COMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),PAG.COMDIA)),2)
WHERE DULE.TIPO = 'CAP3'
UNION ALL
--170
--TABLA CACOMDIS
SELECT RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE,DULE.END_DATE, CASE WHEN DULE.END_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2) then  CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2)
ELSE 
CASE when DULE.END_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMDIA)),2) then CONVERT(VARCHAR(MAX),COMDIS.CDMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMDIA)),2)
ELSE 
CASE WHEN DULE.END_DATE = 'R''_''MATURITY' THEN 'R''_''MATURITY'
END END END  END_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CDANCP,CDMECP,CDDICP,CDMANO,CDMMES,CDMDIA FROM CACOMDIS) COMDIS
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(COMDIS.CANUCR))
and DULE.END_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDANCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMECP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDDICP)),2)
and DULE.END_DATE = CONVERT(VARCHAR(MAX),COMDIS.CDMANO)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMMES)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),COMDIS.CDMDIA)),2)
WHERE DULE.TIPO = 'CAP4'
UNION ALL
SELECT  RTRIM(LTRIM(DULE.K_KEY)) K_KEY , RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DULE.START_DATE,
DULE.END_DATE,
CASE
	WHEN BADI.CAFRRE = 13 
		 THEN 'R''_''MATURITY'
    WHEN BADI.CAFRRE = 7 
		 THEN CASE WHEN CONVERT(VARCHAR(MAX),CREDIT.CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDVCP)),2) <= CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2) THEN CONVERT(VARCHAR(MAX),CREDIT.CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDVCP)),2) ELSE CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2) END
	ELSE
		CASE WHEN CONVERT(VARCHAR(MAX),CREDIT.CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDVCP)),2) <= CONVERT(VARCHAR(MAX),BADI.CAAVRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMVRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADVRE)),2) THEN CONVERT(VARCHAR(MAX),CREDIT.CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDVCP)),2) ELSE CONVERT(VARCHAR(MAX),BADI.CAAVRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMVRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADVRE)),2) END
	END END_DATE_AUDITORIA
FROM MIG_TAKE_OVER_SCHEDULE DULE
LEFT JOIN CACREDIT CREDIT
ON RTRIM(LTRIM(DULE.K_KEY)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT DISTINCT CANUCR,CAFRRE,CAASRE,CAMSRE,CADSRE,CAAVRE,CAMVRE,CADVRE FROM CACOBADI) BADI
ON  RTRIM(LTRIM(RIGHT(DULE.K_KEY,7))) = RTRIM(LTRIM(BADI.CANUCR))
AND DULE.END_DATE = CONVERT(VARCHAR(MAX),CREDIT.CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CREDIT.CRDVCP)),2)
AND DULE.END_DATE = CONVERT(VARCHAR(MAX),BADI.CAASRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMSRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADSRE)),2)
--AND DULE.END_DATE = CONVERT(VARCHAR(MAX),DISCAP.DSAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP.DSMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),DISCAP.DSDVCP)),2)
AND DULE.END_DATE = CONVERT(VARCHAR(MAX),BADI.CAAVRE)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CAMVRE)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),BADI.CADVRE)),2)
WHERE DULE.TIPO = 'INT'
)X)

--SELECT K_KEY, K_KEY_AUDITORIA FROM CTE3
--WHERE K_KEY <> K_KEY_AUDITORIA

SELECT END_DATE, END_DATE_AUDITORIA FROM CTE3
WHERE END_DATE <> END_DATE_AUDITORIA