--MIG_CHARGE_OFF_ACTIVITY
--TOTAL 34,119


WITH CTE AS(
SELECT distinct CHARGE.ARRANGEMENT , RTRIM(LTRIM('L'+CREDIT.CANUCR)) ARRANGEMENT_AUDITORIA,
CHARGE.UPLOAD_COMPANY , SUC.COMPANY UPLOAD_COMPANY_AUDITORIA,
CHARGE.EFFECTIVE_DATE, CONVERT(VARCHAR(MAX),CAH.CAAETR)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAH.CAMETR)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAH.CADETR)),2) EFFECTIVE_DATE_AUDITORIA,
CHARGE.TXN_AMOUNT, CAH.CACAPI TXN_AMOUNT_AUDITORIA5,
CHARGE.CURRENCY, 
CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
WHEN CREDIT.PRMONE = 034 THEN 'USD'
WHEN CREDIT.PRMONE IN (035,004) THEN 'EUR' END AS CURRENCY_AUDITORIA
FROM MIG_CHARGE_OFF_ACTIVITY CHARGE
LEFT JOIN   CACREDIT CREDIT ON CHARGE.ARRANGEMENT = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN MIG_HOM_SUCURSAL SUC
ON CHARGE.UPLOAD_COMPANY = SUC.COMPANY
LEFT JOIN (SELECT DISTINCT CANUCR,CAAETR,CAMETR,CADETR,CACAPI FROM  CAHISPTM) CAH ON RTRIM(LTRIM('L'+CREDIT.CANUCR)) = RTRIM(LTRIM('L'+CAH.CANUCR))
AND CHARGE.EFFECTIVE_DATE = CONVERT(VARCHAR(MAX),CAH.CAAETR)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAH.CAMETR)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAH.CADETR)),2)
AND CHARGE.TXN_AMOUNT = CAH.CACAPI 
)


----ARRANGEMENT VS ARRANGEMENT_AUDITORIA
--SELECT ARRANGEMENT , ARRANGEMENT_AUDITORIA FROM CTE
--WHERE ARRANGEMENT <> ARRANGEMENT_AUDITORIA


----UPLOAD_COMPANY VS UPLOAD_COMPANY_AUDITORIA
--SELECT UPLOAD_COMPANY , UPLOAD_COMPANY_AUDITORIA FROM CTE
--WHERE UPLOAD_COMPANY <> UPLOAD_COMPANY_AUDITORIA


----EFFECTIVE_DATE VS EFFECTIVE_DATE_AUDITORIA
--SELECT EFFECTIVE_DATE , EFFECTIVE_DATE_AUDITORIA FROM CTE
--WHERE EFFECTIVE_DATE <> EFFECTIVE_DATE_AUDITORIA

----TXN_AMOUNT VS TXN_AMOUNT_AUDITORIA
--SELECT TXN_AMOUNT , TXN_AMOUNT_AUDITORIA FROM CTE
--WHERE TXN_AMOUNT <> TXN_AMOUNT_AUDITORIA


----CURRENCY VS CURRENCY_AUDITORIA
--SELECT CURRENCY , CURRENCY_AUDITORIA FROM CTE
--WHERE CURRENCY <> CURRENCY_AUDITORIA