--MIG_TAKE_OVER_XTIDOM
--TOTAL 213,933

WITH CTE AS(
SELECT DOM.K_KEY, RTRIM(LTRIM('L'+CREDIT.CANUCR)) K_KEY_AUDITORIA,
DOM.STATUS_TIDOM, CASE   
    WHEN CREDIT.CAORFF < 900    
        THEN 1 
    WHEN CREDIT.CAORFF >= 900   
        THEN 3 
    ELSE 
        0 
END 
    AS STATUS_TIDOM_AUDITORIA,
DOM.NO_TIDOM, TITU.TITULARIZADORA AS NO_TIDOM_AUDITORIA
FROM  MIG_TAKE_OVER_XTIDOM DOM
LEFT JOIN CACREDIT CREDIT ON DOM.K_KEY = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN MIG_HOM_TITULIZADORA TITU
ON CREDIT.CAORFF = TITU.CAORFF
)

----CANTIDAD QUE SE IMPORTO
--SELECT COUNT(*) FROM CTE


----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY , K_KEY_AUDITORIA FROM CTE 
--WHERE K_KEY <> K_KEY_AUDITORIA

----STATUS_TIDOM VS STATUS_TIDOM_AUDITORIA
--SELECT STATUS_TIDOM , STATUS_TIDOM_AUDITORIA FROM CTE
--WHERE STATUS_TIDOM <> STATUS_TIDOM_AUDITORIA


----NO_TIDOM VS NO_TIDOM_AUDITORIA
--SELECT NO_TIDOM , NO_TIDOM_AUDITORIA FROM CTE
--WHERE NO_TIDOM <> NO_TIDOM_AUDITORIA




