--MIG_TAKE_OVER_ACCOUNT
--Total: 213,933

WITH CTE AS(
SELECT ACCO.ALT_ID , RTRIM(LTRIM('L'+CREDIT.CANUCR)) ALT_ID_AUDITORIA
FROM MIG_TAKE_OVER_ACCOUNT ACCO
LEFT JOIN CACREDIT CREDIT ON ACCO.ALT_ID = RTRIM(LTRIM('L'+CREDIT.CANUCR))
INNER JOIN ( SELECT CANUCR FROM DISCAP_DIS_SIM_SALD_SIMPLES UNION SELECT CANUCR FROM DISCAP_DIS_SIM_SALD_EX_DIST ) DISCAP
ON RTRIM(LTRIM(CREDIT.CANUCR)) = RTRIM(LTRIM(DISCAP.CANUCR))
)

----TOTAL DE LA TABLA QUE SE IMPORTO
--SELECT COUNT(*) FROM CTE 

----ALT_ID VS ALT_ID_AUDITORIA
--SELECT ALT_ID, ALT_ID_AUDITORIA FROM CTE
--WHERE ALT_ID <> ALT_ID_AUDITORIA


