--TAKE OVER
--159,339

--WITH CTE AS(
SELECT DISTINCT  A.K_KEY, RTRIM(LTRIM('L'+B.CANUCR)) K_KEY_AUDITORIA,A.UPLOAD_COMPANY UPLOAD_COMPANY, SUC.COMPANY UPLOAD_COMPANY_AUDITORIA, 
REPLACE(A.CUSTOMER ,'::','')CUSTOMER, REPLACE(X.CUSTOMER,'::','') AS CUSTOMER_AUDITORIA, A.CUSTOMER_ROLE, CASE
WHEN X.CUSTOMER_ROLE = '::OWNER' THEN 'OWNER'
WHEN X.CUSTOMER_ROLE = '::OWNER::JOINT.OWNER' THEN 'OWNER::JOINT.OWNER'
END  CUSTOMER_ROLE_AUDITORIA,
A.PRODUCT,  ISNULL(PROD7X.PRODUCT,PROD.PRODUCT) PRODUCTO_AUDITORIA, A.CURRENCY, 
CASE WHEN B.PRMONE = 000 THEN 'DOP' 
WHEN B.PRMONE = 034 THEN 'USD'
WHEN B.PRMONE IN (035,004) THEN 'EUR' END AS CURRENCY_AUDITORIA,
A.ORIG_CONTRACT_DATE, 
 CONVERT(VARCHAR(MAX),CAACOC)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CAMCOC)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CADCOC)),2) AS ORIG_CONTRACT_DATE_AUDITORIA,
A.MATURITY_DATE,
CONVERT(VARCHAR(MAX),CRAVCP)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CRMVCP)),2)+''+right(('00'+''+CONVERT(VARCHAR(MAX),CRDVCP)),2) AS MATURITY_DATE_AUDITORIA
FROM MIG_TAKE_OVER_AUDITORIA A
LEFT JOIN CACREDIT B ON RTRIM(LTRIM(A.AAA_ID)) = RTRIM(LTRIM('L'+B.CANUCR))
INNER JOIN ( SELECT CANUCR, CORRELATIVO FROM DISCAP_DIS_SIM_SALD_SIMPLES UNION SELECT CANUCR, DS_CORR FROM DISCAP_DIS_SIM_SALD_EX_DIST
) DISCAP
ON RTRIM(LTRIM(B.CANUCR)) = TRIM(DISCAP.CANUCR)
LEFT JOIN TAKE_OVER_HELP_CUSTOMERS X
ON RTRIM(LTRIM(X.CANUCR)) = RTRIM(LTRIM(B.canucr))
LEFT JOIN MIG_HOM_SUCURSAL SUC
ON A.UPLOAD_COMPANY = SUC.COMPANY
LEFT JOIN MIG_HOM_PRODUCT PROD
ON A.CAPROD = PROD.CAPROD
AND A.CASUBP = PROD.CASUBP	
AND PROD.PLANTILLA = CASE WHEN DISCAP.CORRELATIVO IS NOT NULL THEN 'D' ELSE 'S' END
AND CASE WHEN DISCAP.CORRELATIVO IS NOT NULL THEN DISCAP.CORRELATIVO ELSE 1 END = CASE WHEN DISCAP.CORRELATIVO IS NOT NULL THEN cast(rtrim(ltrim(prod.CORR)) as numeric) ELSE 1 END
LEFT JOIN ACTAB1 TAB1
ON TAB1.CODTAB = 'K7'
AND B.CAPROD = 1
AND B.CASUBP IN (70,71)
AND RTRIM(LTRIM(B.AXASER)) = RTRIM(LTRIM(TAB1.CODELE))
LEFT JOIN MIG_HOM_PRODUCT_70_71 PROD7X
ON A.CAPROD = PROD7X.CAPROD
AND A.CASUBP = PROD7X.CASUBP
AND ISNULL(RTRIM(LTRIM(TAB1.SW02)),'P') = RTRIM(LTRIM(PROD7X.SW02))
AND A.PRODUCT =  ISNULL(PROD7X.PRODUCT,PROD.PRODUCT)
--)


--PARA LA VALIDACION PROCEDA A DESCOMENTAR Y LUEGO EJECUTAR

----VALIDAR LA CANTIDAD DE REGISTRO GLOBAL
--SELECT * FROM CTE

----K_KEY VS K_KEY_AUDITORIA
--SELECT K_KEY,K_KEY_AUDITORIA FROM CTE
--WHERE  K_KEY <> K_KEY_AUDITORIA 

----UPLOAD_COMPANY VS UPLOAD_COMPANY_AUDITORIA
--SELECT UPLOAD_COMPANY,UPLOAD_COMPANY_AUDITORIA FROM CTE 
--WHERE UPLOAD_COMPANY <> UPLOAD_COMPANY_AUDITORIA

----CUSTOMER VS CUSTOMER_AUDITORIA
--SELECT CUSTOMER,CUSTOMER_AUDITORIA FROM CTE
--WHERE CUSTOMER <> CUSTOMER_AUDITORIA


----CUSTOMER_ROLE VS CUSTOMER_ROLE_AUDITORIA
--SELECT CUSTOMER_ROLE,CUSTOMER_ROLE_AUDITORIA FROM CTE
--WHERE CUSTOMER_ROLE <> CUSTOMER_ROLE_AUDITORIA

----PRODUCT VS PRODUCTO_ACUDITORIA
--SELECT K_KEY,PRODUCT,PRODUCTO_AUDITORIA FROM CTE
--WHERE PRODUCT <> PRODUCTO_AUDITORIA


----CURRENCY VS CURRENCY_AUDITORIA
--SELECT K_KEY,CURRENCY,CURRENCY_AUDITORIA FROM CTE
--WHERE CURRENCY<>CURRENCY_AUDITORIA


----ORIG_CONTRACT_DATE VS ORIG_CONTRACT_DATE_AUDITORIA
--SELECT ORIG_CONTRACT_DATE, ORIG_CONTRACT_DATE_AUDITORIA FROM CTE
--WHERE ORIG_CONTRACT_DATE<> ORIG_CONTRACT_DATE_AUDITORIA

----MATURITY_DATE VS MATURITY_DATE_AUDITORIA
--SELECT K_KEY, MATURITY_DATE, MATURITY_DATE_AUDITORIA FROM CTE
--WHERE MATURITY_DATE<> MATURITY_DATE_AUDITORIA