--MIG_ADVANCE_PAYMENT_DIST
--TOTAL 2,374
--2,276
SELECT DISTINCT PAY.CREDIT_ACCOUNT, RTRIM(LTRIM('LA'+CREDIT.CANUCR)) AS CREDIT_CANUCR ,
PAY.DEBIT_CCY, CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
					 WHEN CREDIT.PRMONE = 034 THEN 'USD'
					 WHEN CREDIT.PRMONE IN (035,004) THEN 'EU' END AS MONEDA_CREDIT,
PAY.PAYMENT_AMOUNT, abs((coalesce(DISCAP2.DSMATA,0) + COALESCE(DISCAP2.DSINAC,0) + COALESCE(BADI.CARET1,0)))  AS PAYMENT_AMOUNT_OMAR
FROM MIG_ADVANCE_PAYMENT_DIST_LA PAY
LEFT JOIN CACREDIT CREDIT
ON  RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
LEFT JOIN (SELECT  DISTINCT CANUCR, SUM(CARET1) AS CARET1 FROM CACOBADI GROUP BY CANUCR) BADI
ON RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('LA'+BADI.CANUCR))
LEFT JOIN   CADISCAP DISCAP2 
ON   RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('LA'+DISCAP2.CANUCR)) --AND  DISCAP2.DSCORR = 2
AND PAY.PAYMENT_AMOUNT = abs((coalesce(DISCAP2.DSMATA,0) + COALESCE(DISCAP2.DSINAC,0) + COALESCE(BADI.CARET1,0)))
--WHERE PAY.CREDIT_ACCOUNT = 'LA3010249'
UNION all
----98
SELECT DISTINCT PAY.CREDIT_ACCOUNT, RTRIM(LTRIM('LB'+CREDIT.CANUCR)) AS CREDIT_CANUCR,
				PAY.DEBIT_CCY, CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
					 WHEN CREDIT.PRMONE = 034 THEN 'USD'
					 WHEN CREDIT.PRMONE IN (035,004) THEN 'EU' END AS MONEDA_CREDIT,
		PAY.PAYMENT_AMOUNT,abs((coalesce(DISCAP2.DSMATA,0) + COALESCE(DISCAP2.DSINAC,0)))  AS PAYMENT_AMOUNT_OMAR
FROM  MIG_ADVANCE_PAYMENT_DIST_LB PAY 
LEFT JOIN CACREDIT CREDIT
ON  RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('LB'+CREDIT.CANUCR))
LEFT JOIN   CADISCAP DISCAP2 
ON   RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('LB'+DISCAP2.CANUCR))
AND PAY.PAYMENT_AMOUNT =  abs((coalesce(DISCAP2.DSMATA,0) + COALESCE(DISCAP2.DSINAC,0)))
----WHERE PAY.CREDIT_ACCOUNT = 'LB3901145'







