--ADVANCE PAYMENT SIMPLES 34,566

SELECT DISTINCT PAY.CREDIT_ACCOUNT, RTRIM(LTRIM('L'+CREDIT.CANUCR)) AS CREDIT_CANUCR,
	   PAY.DEBIT_CCY, CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
					 WHEN CREDIT.PRMONE = 034 THEN 'USD'
					 WHEN CREDIT.PRMONE IN (035,004) THEN 'EU' END AS MONEDA_CREDIT,
	   PAY.PAYMENT_CURRENCY, CASE WHEN CREDIT.PRMONE = 000 THEN 'DOP' 
					 WHEN CREDIT.PRMONE = 034 THEN 'USD'
					 WHEN CREDIT.PRMONE IN (035,004) THEN 'EU' END AS MONEDA_CREDIT,
	 PAY.PAYMENT_AMOUNT, abs((coalesce(CREDIT.CAATRA,0) + COALESCE(CREDIT.CAINAC,0) + COALESCE(BADI.CARET1,0))) AS PAYMENT_AMOUNT_OMAR
FROM  MIG_ADVANCE_PAYMENT PAY
LEFT JOIN CACREDIT CREDIT
ON  RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('L'+CREDIT.CANUCR))
LEFT JOIN (SELECT  DISTINCT CANUCR, SUM(CARET1) AS CARET1 FROM CACOBADI GROUP BY CANUCR) BADI
ON RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('L'+BADI.CANUCR))
 AND PAY.PAYMENT_AMOUNT =   abs((coalesce(CREDIT.CAATRA,0) + COALESCE(CREDIT.CAINAC,0) + COALESCE(BADI.CARET1,0)))
--LEFT JOIN (SELECT CANUCR, CARET1  FROM CACOBADI GROUP BY CANUCR, CARET1) BADI 
--ON RTRIM(LTRIM(PAY.CREDIT_ACCOUNT)) = RTRIM(LTRIM('L'+BADI.CANUCR))
--AND PAY.PAYMENT_AMOUNT =  CREDIT.CAATRA + CREDIT.CAINAC + BADI.CARET1
--WHERE PAY.CREDIT_ACCOUNT =  'L0597048'
ORDER BY PAY.CREDIT_ACCOUNT


--SELECT CAATRA, CAINAC FROM CACREDIT
--SELECT CARET1 FROM CACOBADI

