--LIMIT_LC
--27,830

WITH CTE AS(
SELECT LC.UPLOAD_COMPANY,CASE WHEN EXISTS(SELECT SUCL.COMPANY INTERSECT SELECT NULL) THEN CR.SUCURSAL_T24 ELSE SUCL.COMPANY END UPLOAD_COMPANY_AUDITORIA,
LC.LIMIT_CURRENCY, MHC.CURRENCY_V LIMIT_CURRENCY_AUDITORIA,
LC.EXPIRY_DATE,
CASE WHEN LCL.LIFVEN <= 20210621 THEN 20210622 ELSE LCL.LIFVEN END AS EXPIRY_DATE_AUDITORIA,
LC.CUSTOMER_NUMBER, CR.CUSTOMER_CODE CUSTOMER_NUMBER_AUDITORIA
FROM MIG_LIMIT_LC2 LC
LEFT JOIN (SELECT DISTINCT LIFVEN FROM LCLINEA) LCL 
ON LC.EXPIRY_DATE = LCL.LIFVEN
LEFT JOIN MIG_HOM_CURRENCY MHC ON LC.LIMIT_CURRENCY = MHC.CURRENCY_V
LEFT JOIN (SELECT DISTINCT SUCURSAL_T24,CUSTOMER_CODE FROM CUSTOMER_CODE_REL) CR ON LC.CUSTOMER_NUMBER = CR.CUSTOMER_CODE
LEFT JOIN MIG_HOM_SUCURSAL_LIMIT SUCL ON LC.UPLOAD_COMPANY = CASE WHEN EXISTS(SELECT SUCL.COMPANY INTERSECT SELECT NULL) THEN CR.SUCURSAL_T24 ELSE SUCL.COMPANY END
)

--SELECT UPLOAD_COMPANY,UPLOAD_COMPANY_AUDITORIA FROM CTE 
--WHERE UPLOAD_COMPANY <> UPLOAD_COMPANY_AUDITORIA

--SELECT LIMIT_CURRENCY, LIMIT_CURRENCY_AUDITORIA FROM CTE 
--WHERE LIMIT_CURRENCY <> LIMIT_CURRENCY_AUDITORIA


--SELECT EXPIRY_DATE,EXPIRY_DATE_AUDITORIA FROM CTE 
--WHERE EXPIRY_DATE <> EXPIRY_DATE_AUDITORIA


--SELECT CUSTOMER_NUMBER,CUSTOMER_NUMBER_AUDITORIA FROM CTE 
--WHERE CUSTOMER_NUMBER <> CUSTOMER_NUMBER_AUDITORIA


---------------------------------------------------------
----APPROVAL_DATE
--WITH CTE2 AS(
--SELECT   
--		 LC.APPROVAL_DATE,LCL.LIFEAP  APPROVAL_DATE_AUDITORIA
--FROM MIG_LIMIT_LC2 LC
--LEFT JOIN (SELECT DISTINCT LIFEAP FROM LCLINEA) LCL 
--ON LC.APPROVAL_DATE =  LCL.LIFEAP )

--SELECT APPROVAL_DATE,APPROVAL_DATE_AUDITORIA FROM CTE2 
--WHERE APPROVAL_DATE <> APPROVAL_DATE_AUDITORIA




------------------------------------------------------
--INTERNAL_AMOUNT, MAXIMUM_TOTAL, ORIGINAL_LIMIT
WITH CTE3 AS(
SELECT 
CONVERT(DECIMAL(14,2), LC.INTERNAL_AMOUNT)INTERNAL_AMOUNT, ROUND(LCL.LIMAPR,2) AS INTERNAL_AMOUNT_AUDITORIA,
CONVERT(DECIMAL(14,2), LC.MAXIMUM_TOTAL)MAXIMUM_TOTAL, ROUND(LCL.LIMAPR,2) AS MAXIMUM_TOTAL_AUDITORIA,
CONVERT(DECIMAL(14,2), LC.ORIGINAL_LIMIT)ORIGINAL_LIMIT, ROUND(LCL.LIMAPR,2) AS ORIGINAL_LIMIT_AUDITORIA
FROM MIG_LIMIT_LC2 LC
LEFT JOIN (SELECT DISTINCT LIMAPR FROM LCLINEA) LCL 
ON CONVERT(DECIMAL(14,2),LC.INTERNAL_AMOUNT) = ROUND(LCL.LIMAPR,2) 
)

--SELECT INTERNAL_AMOUNT,INTERNAL_AMOUNT_AUDITORIA FROM CTE3 
--WHERE INTERNAL_AMOUNT <> INTERNAL_AMOUNT_AUDITORIA

--SELECT MAXIMUM_TOTAL,MAXIMUM_TOTAL_AUDITORIA FROM CTE3 
--WHERE MAXIMUM_TOTAL <> MAXIMUM_TOTAL_AUDITORIA

--SELECT ORIGINAL_LIMIT,ORIGINAL_LIMIT_AUDITORIA FROM CTE3 
--WHERE ORIGINAL_LIMIT <> ORIGINAL_LIMIT_AUDITORIA



