--CAPTURE BALANCE DISTRIBUIDOS
--10,582
SELECT DISTINCT
	CAP.K_KEY,
CASE
	WHEN RTRIM(LTRIM(CAP.K_KEY)) = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR))
	WHEN RTRIM(LTRIM(CAP.K_KEY)) = RTRIM(LTRIM('LB'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LB'+CREDIT.CANUCR))
	END AS CANUCR_OMAR,
	CAP.UPLOAD_COMPANY, CREDIT.CAAGEN,
	CAP.AAA_ID,
CASE
	WHEN RTRIM(LTRIM(CAP.AAA_ID)) = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LA'+CREDIT.CANUCR))
	WHEN RTRIM(LTRIM(CAP.AAA_ID)) = RTRIM(LTRIM('LB'+CREDIT.CANUCR)) THEN RTRIM(LTRIM('LB'+CREDIT.CANUCR))
	END AS AAA_ID_CANUCR_OMAR,
	CAP.PRODUCT,ISNULL(PROD7X.PRODUCT,PROD.PRODUCT) PRODUCTO_OMAR
FROM MIG_CAPTURE_BALANCE_D CAP
LEFT JOIN  CACREDIT CREDIT
ON	RTRIM(LTRIM(CAP.K_KEY)) = RTRIM(LTRIM('LA'+CREDIT.CANUCR)) 
OR	RTRIM(LTRIM(CAP.K_KEY)) = RTRIM(LTRIM('LB'+CREDIT.CANUCR))
LEFT JOIN MIG_HOM_PRODUCT PROD
ON CREDIT.CAPROD = PROD.CAPROD
AND CREDIT.CASUBP = PROD.CASUBP
AND PROD.PLANTILLA = 'S'
LEFT JOIN ACTAB1 TAB1
ON TAB1.CODTAB = 'K7'
AND CREDIT.CAPROD = 1
AND CREDIT.CASUBP IN (70,71)
AND RTRIM(LTRIM(CREDIT.AXASER)) = RTRIM(LTRIM(TAB1.CODELE))
LEFT JOIN MIG_HOM_PRODUCT_70_71 PROD7X
ON CREDIT.CAPROD = PROD7X.CAPROD
AND CREDIT.CASUBP = PROD7X.CASUBP
AND ISNULL(RTRIM(LTRIM(TAB1.SW02)),'P') = RTRIM(LTRIM(PROD7X.SW02))
