SELECT * FROM MIG_HOM_SUCURSAL
ORDER BY CODIGO

-- Scrip para validar integridad de Prestamos castigados

SELECT DISTINCT a.CANUCR,RIGHT(c.UPLOAD_COMPANY,3),a.CAAGEN CAAGEN,
CASE
WHEN a.PRMONE = '000' THEN 'DOP'
WHEN a.PRMONE = '034' THEN 'USD'
WHEN a.PRMONE = '004' THEN 'EUR'
WHEN a.PRMONE = '035' THEN 'EUR' END AS PRMONE ,c.CURRENCY,c.TXN_AMOUNT,b.CACAPI, A.CACAVI
FROM CACREDIT a 
	 JOIN 
	 MIG_CHARGE_OFF_ACTIVITY c 
	 ON a.CANUCR = RIGHT(c.ARRANGEMENT,7)
	 LEFT JOIN 
	 CAHISPTM b 
	 ON a.CANUCR = b.CANUCR --AND b.CATIPO = 'STA' AND CAHIS5 = 40
	 JOIN MIG_HOM_SUCURSAL d
	 ON a.CAAGEN = d.CODIGO
 --WHERE CACSTC = 40 AND SBSTCA = 40   
     
ORDER BY a.CANUCR

SELECT CACAVI FROM CACREDIT WHERE CANUCR = '0571788' 

SELECT * FROM CURRENCY

SELECT DISTINCT a.CANUCR,
case WHEN a.CAAGEN = RIGHT(c.UPLOAD_COMPANY,3) THEN a.CAAGEN ELSE 'DIFERENTE' END AS OFICINA
,a.PRMONE,c.CURRENCY,c.TXN_AMOUNT - b.CACAPI
FROM CACREDIT a 
	 JOIN 
	 MIG_CHARGE_OFF_ACTIVITY c 
	 ON a.CANUCR = RIGHT(c.ARRANGEMENT,7)
	 LEFT JOIN 
	 CAHISPTM b 
	 ON a.CANUCR = b.CANUCR AND b.CATIPO = 'STA' AND CAHIS5 = 40
	 JOIN MIG_HOM_SUCURSAL d
	 ON a.CAAGEN = d.CODIGO
 WHERE CACSTC = 40 AND SBSTCA = 40     
     
ORDER BY a.CANUCR

