--LIMIT CONTRATO
--TOTAL 1,023
select
TRATO.UPLOAD_COMPANY , CORE.SUCURSAL_T24 ,
TRATO.APPROVAL_DATE, CASE WHEN CONVERT(VARCHAR,CONT.FECHA_ELABORADO_CTR,112) >= 20210517 THEN '20210517' ELSE CONVERT(VARCHAR,CONT.FECHA_ELABORADO_CTR,112) END APPROVAL_DATE_AUDITORIA,
TRATO.REVIEW_FREQUENCY, CASE WHEN CONVERT(VARCHAR,CONT.FECHA_VENCIMIENTO_CTR,112) <= 20210517 THEN 'M1218' ELSE 'M12' + SUBSTRING(CONT.FECHA_VENCIMIENTO_CTR,1,2) END REVIEW_FREQUENCY_AUDITORIA,
TRATO.EXPIRY_DATE,
CASE
  WHEN convert(varchar,FECHA_VENCIMIENTO_CTR,112)  <= 20210517 THEN '20210518'
  ELSE convert(varchar,FECHA_VENCIMIENTO_CTR,112)
END EXPIRY_DATE_AUDITORIA,
TRATO.INTERNAL_AMOUNT, CONT.VALOR_CTR,
TRATO.MAXIMUM_TOTAL, CONT.VALOR_CTR,
TRATO.ORIGINAL_LIMIT, CONT.VALOR_CTR,
TRATO.CUSTOMER_NUMBER,CORE.CUSTOMER_CODE,
TRATO.LOCAL_REF ,  HELP.CONTRATO
from MIG_LIMIT_CONTRATO TRATO
left JOIN (select DISTINCT convert(varchar,FECHA_VENCIMIENTO_CTR,112) as FECHA_VENCIMIENTO_CTR,CONVERT(VARCHAR,FECHA_ELABORADO_CTR,112) FECHA_ELABORADO_CTR, VALOR_CTR  from KIM_CONTRATO_2) CONT
ON  TRATO.APPROVAL_DATE = CASE WHEN CONVERT(VARCHAR,FECHA_ELABORADO_CTR,112) >= 20210517 THEN '20210517' ELSE CONVERT(VARCHAR,CONT.FECHA_ELABORADO_CTR,112) END
AND TRATO.EXPIRY_DATE = CASE
  WHEN convert(varchar,CONT.FECHA_VENCIMIENTO_CTR,112)  <= 20210621 THEN '20210517'
  ELSE convert(varchar,CONT.FECHA_VENCIMIENTO_CTR,112)
END
AND TRATO.REVIEW_FREQUENCY = CASE WHEN CONVERT(VARCHAR,CONT.FECHA_VENCIMIENTO_CTR,112) <= 20210621 THEN 'M1218' ELSE 'M12' + SUBSTRING(CONT.FECHA_VENCIMIENTO_CTR,1,2) END
AND TRATO.INTERNAL_AMOUNT= CONT.VALOR_CTR
AND TRATO.MAXIMUM_TOTAL = CONT.VALOR_CTR
AND TRATO.ORIGINAL_LIMIT= CONT.VALOR_CTR
LEFT JOIN (SELECT DISTINCT CUSTOMER_CODE, SUCURSAL_T24 FROM  customer_code_rel  ) CORE
ON TRATO.UPLOAD_COMPANY = CORE.SUCURSAL_T24 
AND TRATO.CUSTOMER_NUMBER =CORE.CUSTOMER_CODE 
LEFT JOIN (SELECT DISTINCT CONTRATO FROM  MIG_HOM_LIMIT_HELPER_CONTRATO) CONT2
ON TRATO.LOCAL_REF =  CONT2.CONTRATO





--TRUNCATE TABLE Cliente
SELECT 
 CAST(TRATO.INTERNAL_AMOUNT AS DECIMAL(14,2))INTERNAL_AMOUNT, CONT.VALOR_CTR INTERNAL_AMOUNT_AUDITORIA,
 CAST(TRATO.MAXIMUM_TOTAL AS DECIMAL(14,2))MAXIMUM_TOTAL , CONT.VALOR_CTR MAXIMUM_TOTAL_AUDITORIA,
 CAST(TRATO.ORIGINAL_LIMIT AS DECIMAL(14,2))ORIGINAL_LIMIT, CONT.VALOR_CTR ORIGINAL_LIMIT_AUDITORIA
FROM  MIG_LIMIT_CONTRATO TRATO
LEFT JOIN (SELECT DISTINCT VALOR_CTR FROM KIM_CONTRATO_2) CONT
ON CAST(TRATO.INTERNAL_AMOUNT AS DECIMAL(14,2))= CONT.VALOR_CTR
--AND CAST(TRATO.MAXIMUM_TOTAL AS DECIMAL(14,2)) = CONT.VALOR_CTR
--AND CAST(TRATO.ORIGINAL_LIMIT AS DECIMAL(14,2))= CONT.VALOR_CTR
WHERE CONT.VALOR_CTR IS NULL

