--LIMIT LC
--10,388

SELECT LIMIT_LC.UPLOAD_COMPANY, CASE WHEN EXISTS(SELECT SUCL.COMPANY INTERSECT SELECT NULL) THEN CR.SUCURSAL_T24 ELSE SUCL.COMPANY END COMPANY,
	    LIMIT_LC.APPROVAL_DATE, LCL.LIFEAP,
		LIMIT_LC.REVIEW_FREQUENCY, CASE WHEN LCL.LIFREV <= 20210621 THEN 'M1218' ELSE 'M12' + SUBSTRING(CAST(LCL.LIFREV AS VARCHAR(MAX)),7,2) END AS REVIEW_FREQUENCY,
		LIMIT_LC.EXPIRY_DATE, CASE WHEN LCL.LIFVEN <= 20210517 THEN '20210518' ELSE CAST(COALESCE(LCL.LIFVEN,0) AS VARCHAR(MAX)) END AS EXPIRY_DATE,
		LIMIT_LC.NOTES, 'F.ORIG '+CAST(LCL.LIFCER AS VARCHAR(MAX))+' F.REV '+CAST(LCL.LIFREV AS VARCHAR(MAX))+'::F.APROB '+CAST(LCL.LIFEAP AS VARCHAR(MAX)),
		CONVERT(DECIMAL(14,2),LIMIT_LC.INTERNAL_AMOUNT)INTERNAL_AMOUNT, LCL.LIMAPR,
		CONVERT(DECIMAL(14,2),LIMIT_LC.MAXIMUM_TOTAL)MAXIMUM_TOTAL, LCL.LIMAPR,
		CONVERT(DECIMAL(14,2),LIMIT_LC.ORIGINAL_LIMIT)ORIGINAL_LIMIT, LCL.LIMAPR,
		LIMIT_LC.CUSTOMER_NUMBER, CR.CUSTOMER_CODE,
		LIMIT_LC.LOCAL_REF, LCL.LINUAP
FROM MIG_LIMIT_LC LIMIT_LC
LEFT JOIN MIG_HOM_SUCURSAL_LIMIT SUCL ON LIMIT_LC.UPLOAD_COMPANY = SUCL.COMPANY
LEFT JOIN LCLINEA LCL ON LIMIT_LC.LOCAL_REF = LCL.LINUAP
LEFT JOIN (SELECT DISTINCT CPMAPR FROM LCCUPOS) LCCU 
ON CONVERT(DECIMAL(14,2),LIMIT_LC.INTERNAL_AMOUNT)=LCCU.CPMAPR 
LEFT JOIN [dbo].[Cliente] CR ON LIMIT_LC.CUSTOMER_NUMBER = CR.CUSTOMER_CODE


	